Ext.define("MyExtGenApp.view.personnel.ReservationViewStore", {
  extend: "Ext.data.Store",
  alias: "store.reservationviewstore",
  fields: [
    "reservationId",
    "reservationCode",
    "price",
    "creationDate",
    "checkInDate",
    "checkOutDate",
  ],
  groupField: "reservationCode",
  data: {
    items: [
      {
        reservationId: 41,
        reservationCode: "Guarantee",
        price: 513.85,
        creationDate: "2005-07-15T00:00:00",
        checkInDate: "2016-01-28T00:00:00",
        checkOutDate: "2012-04-24T00:00:00",
        guests: [
          {
            guestId: 1,
            firstName: "Trycia",
            lastName: "Deckow",
            email: "Fannie_Cassin58@yahoo.com",
            dateOfBirth: "1995-08-06T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
          {
            guestId: 19,
            firstName: "Flavio",
            lastName: "Renner",
            email: "Alfred.Conroy41@gmail.com",
            dateOfBirth: "1990-02-21T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
        ],
      },
      {
        reservationId: 42,
        reservationCode: "Cancelled",
        price: 569.95,
        creationDate: "2009-12-05T00:00:00",
        checkInDate: "2014-07-28T00:00:00",
        checkOutDate: "2018-02-28T00:00:00",
        guests: [
          {
            guestId: 10,
            firstName: "Shania",
            lastName: "Keebler",
            email: "Delbert.Schaden@gmail.com",
            dateOfBirth: "1986-09-15T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
        ],
      },
      {
        reservationId: 43,
        reservationCode: "Waitlist",
        price: 181.25,
        creationDate: "2013-05-15T00:00:00",
        checkInDate: "2005-11-25T00:00:00",
        checkOutDate: "2008-08-29T00:00:00",
        guests: [
          {
            guestId: 8,
            firstName: "Vivianne",
            lastName: "Tromp",
            email: "Belinda_Conn@gmail.com",
            dateOfBirth: "1997-03-13T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
        ],
      },
      {
        reservationId: 44,
        reservationCode: "Waitlist",
        price: 601.1,
        creationDate: "2005-09-13T00:00:00",
        checkInDate: "2020-03-20T00:00:00",
        checkOutDate: "2019-06-14T00:00:00",
        guests: [
          {
            guestId: 1,
            firstName: "Trycia",
            lastName: "Deckow",
            email: "Fannie_Cassin58@yahoo.com",
            dateOfBirth: "1995-08-06T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
          {
            guestId: 16,
            firstName: "Floy",
            lastName: "Grant",
            email: "Pat62@yahoo.com",
            dateOfBirth: "1993-06-09T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
        ],
      },
      {
        reservationId: 45,
        reservationCode: "Tentative",
        price: 694.66,
        creationDate: "2003-01-09T00:00:00",
        checkInDate: "2002-08-29T00:00:00",
        checkOutDate: "2015-11-24T00:00:00",
        guests: [
          {
            guestId: 8,
            firstName: "Vivianne",
            lastName: "Tromp",
            email: "Belinda_Conn@gmail.com",
            dateOfBirth: "1997-03-13T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
        ],
      },
      {
        reservationId: 46,
        reservationCode: "Guarantee",
        price: 247.59,
        creationDate: "2012-03-10T00:00:00",
        checkInDate: "2013-05-20T00:00:00",
        checkOutDate: "2004-08-25T00:00:00",
        guests: [
          {
            guestId: 4,
            firstName: "Freida",
            lastName: "Kuvalis",
            email: "Mathew_Ledner92@yahoo.com",
            dateOfBirth: "1995-11-02T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
          {
            guestId: 9,
            firstName: "Nora",
            lastName: "Friesen",
            email: "Nina.Rolfson25@hotmail.com",
            dateOfBirth: "1997-08-20T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
        ],
      },
      {
        reservationId: 47,
        reservationCode: "Guarantee",
        price: 575.81,
        creationDate: "2016-03-09T00:00:00",
        checkInDate: "2017-10-15T00:00:00",
        checkOutDate: "2013-11-21T00:00:00",
        guests: [
          {
            guestId: 5,
            firstName: "Theresa",
            lastName: "Nikolaus",
            email: "Francisco.Borer87@hotmail.com",
            dateOfBirth: "1998-07-24T00:00:00",
            zipCode: null,
            phone: null,
            address: null,
            city: null,
            reservations: null,
          },
        ],
      },
    ],
  },
  proxy: {
    type: "memory",
    reader: {
      type: "json",
      rootProperty: "items",
    },
  },
});
